---
title: "Finding Tito - Streets and squares dedicated to Tito in the former Yugoslavia"
author: "Giorgio Comai"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
---

# Introduction

[This document is currently in draft form: please do not cite until this notice is removed.]

**[Click here to see all streets and squares dedicated to Tito identified by this script as an overlay on Google Maps](https://drive.google.com/open?id=1U7EqM2XDLHpyjJaEBy3inOETYg4&usp=sharing).**

## What is this all about?

At this stage, this document represents an effort to find and place on a map all the names of streets and squares that are currently dedicated to Tito in the former Yugoslavia. It advances by trial and error, and suggestions for improvement are accepted.

1. relevant data have been extracted from OpenStreetMap. However, the resulting dataset proved to be incomplete in some areas. 
2. OpenStreetMap data have been used to find common variants relevant street names in each of the countries of the region
3. OpenStreetMap data have been used to extract all names of villages and towns of the region
4. Google Maps has been queried with all combinations of the above, basically "asking" Google Maps if it knew of any "Tito Street", repeating the query for all inhabited locations with more than 1000 inhabitants recorded by OpenStreetMap (tens of thousands of queries in total).
5. The results have been plotted on a map


## How to access this document

Data collection methods and sources are outlined in writing and data processing is presented in both a human and machine readable format. This allows for the process to be as transparent as possible, since all sources are explicitly mentioned, and all the code used for data processing and graph creation is fully explorable. 

Each section introduces data that is then processed to generate composite data and graphs in the ensuing parts. All tables and graphs are available for download in multiple formats.

This document can best be explored from in its online version, currently available at [https://giocomai.github.io/FindingTito/](https://giocomai.github.io/FindingTito/). A table of contents is by default always visible on the left part of the screen. Clicking on the left or right part of the screen allows to "turn pages", thus opening the previous/next section. 

By hovering with the mouse on the top part of the screen, it is possible to access additional customisation options, including the possibility to hide the table of contents, and to change font size and colour. There is also an edit button, which allows to suggest changes to the author (feedback is welcome also by email). 

This document can also be downloaded in [pdf](https://giocomai.github.io/FindingTito/FindingTito.pdf), or [epub format](https://giocomai.github.io/FindingTito/FindingTito.epub) for ebook readers. 

The full source code of this book, including all text and code used for data processing and data visualisation is currently [available on GitHub](https://github.com/giocomai/FindingTito).

Once the document is completed, it will be uploaded to an established academic repository in order to facilitate referencing. 
